// config.js
export const SLIDEOUT_ANIMATION_DURATION = 400;
export const ANIMATION_DURATION = 500;
export const NOTIFICATION_DURATION = 10000;
export const CENTER_POPUP_DURATION = 2000;
export const UPGRADE_COST_MULTIPLIER = 1.15;
export const BASE_EXPANSION_PROBABILITY = 0.005;
export const EXPANSION_DIFFICULTY_FACTOR = 0.1;
export const POPULATION_CONTROL_GAME_OVER_THRESHOLD = 51;
export const EXPANSION_ANIMATION_CIRCLE_RADIUS_INCREMENT = 1;
export const EXPANSION_ANIMATION_CIRCLE_MAX_RADIUS = 100;
export const EXPANSION_ANIMATION_INTERVAL_MS = 10;
export const MIN_POLICE_RESISTANCE_EFFECT = 0.1;
export const DOMINANCE_FACTOR_MULTIPLIER = 2;
export const MONEY_ICON_SPAWN_INTERVAL = 30000;
export const ESBIRROS_ICON_SPAWN_INTERVAL = 40000;
export const POLICE_ICON_SPAWN_INTERVAL = 45000; 